import { defineConfig } from 'oxlint';
export default defineConfig({
  jsPlugins: [{ name: 'anti-slop', specifier: 'oxlint-plugin-anti-slop' }],
  rules: {
    'anti-slop/cognitive-complexity': ['error', 15],
    'anti-slop/cyclomatic-complexity': ['error', { threshold: 12 }],
    'anti-slop/max-lines': ['error', { maximum: 500 }],
    'anti-slop/max-lines-per-function': ['error', { maximum: 80 }],
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
  },
});
