import { createRequire } from 'node:module';
import { join } from 'node:path';
import type { Request, Response } from 'express';
import type { createApp as createNestApp } from '../server/bootstrap';
import { FixtureRunner } from '../tests/fixtures';

// The compiled backend preserves Nest decorator metadata and its static asset path.
const load = createRequire(join(process.cwd(), 'package.json'));
// SAFETY: this module is generated by our TypeScript build from server/bootstrap.ts.
const { createApp } = load('./dist/server/bootstrap.js') as {
  createApp: typeof createNestApp;
};
async function main() {
  const runner = new FixtureRunner();
  const app = await createApp(runner);
  const adapter = app.getHttpAdapter();
  adapter.post('/__fixture/reset', (_req: Request, res: Response) => {
    runner.reset();
    res.json({ status: 'ok' });
  });
  adapter.get('/__fixture/commands', (_req: Request, res: Response) => {
    res.json(runner.commands);
  });
  await app.listen(9877, '127.0.0.1');
}
void main();
